---
name: TCrawler

### database settings. at least one database connection must be defined
database:
    - label : "DB"
      type  : "pg"
      host  : "localhost"
      db    : "tcrawlerdb"
      user  : "tcrawler"
      pass  : "tcrawler"
      proxy : "http://user_name:password@server:port"


tcrawler:
      data_dir: "lib/../data"